

import {useState} from 'react';
import Box from '@mui/material/Box' 
import TextField from '@mui/material/TextField' 
import Tabs from '@mui/material/Tabs';
import Tab from '@mui/material/Tab';
import { PropTypes } from 'prop-types';
import Typography from '@mui/material/Typography';

function TabPanel(props) {
  const { children, value, index, ...other } = props;

  return (
    <div
      role="tabpanel"
      hidden={value !== index}
      id={`simple-tabpanel-${index}`}
      aria-labelledby={`simple-tab-${index}`}
      {...other}
    >
      {value === index && (
        <Box sx={{ p: 3 }}>
          <div>{children}</div>
        </Box>
      )}
    </div>
  );
}

TabPanel.propTypes = {
  children: PropTypes.node,
  index: PropTypes.number.isRequired,
  value: PropTypes.number.isRequired,
};

function a11yProps(index) {
  return {
    id: `simple-tab-${index}`,
    'aria-controls': `simple-tabpanel-${index}`,
  };
}

export default function Stock() {

  const apiOn = false;
  // fill stock data from overview call in alpha vantage
  const stockData = {
    '50DayMovingAverage':"126.57",
    '52WeekHigh': "149.31",
    '52WeekLow':"111.29",
    '200DayMovingAverage': "132.84",
    'Address': "1 NEW ORCHARD ROAD, ARMONK, NY, US",
    'AnalystTargetPrice':"140.79",
    'AssetType':"Common Stock",
    'Beta':"0.851",
    'BookValue':"23.79",
    'CIK':"51143",
    'Country':"USA",
    'Currency':"USD",
    'Description':"International Business Machines Corporation (IBM) is an American multinational technology company headquartered in Armonk, New York, with operations in over 170 countries. The company began in 1911, founded in Endicott, New York, as the Computing-Tabulating-Recording Company (CTR) and was renamed International Business Machines in 1924. IBM is incorporated in New York. IBM produces and sells computer hardware, middleware and software, and provides hosting and consulting services in areas ranging from mainframe computers to nanotechnology. IBM is also a major research organization, holding the record for most annual U.S. patents generated by a business (as of 2020) for 28 consecutive years. Inventions by IBM include the automated teller machine (ATM), the floppy disk, the hard disk drive, the magnetic stripe card, the relational database, the SQL programming language, the UPC barcode, and dynamic random-access memory (DRAM). The IBM mainframe, exemplified by the System/360, was the dominant computing platform during the 1960s and 1970s.",
    'DilutedEPSTTM':"2.24",
    'DividendDate':"2023-06-10",
    'DividendPerShare':"6.6",
    'DividendYield':"0.0515",
    'EBITDA':"12644000000",
    'EPS':"2.24",
    'EVToEBITDA':"25.81",
    'EVToRevenue':"2.969",
    'ExDividendDate':"2023-05-09",
    'Exchange':"NYSE",
    'FiscalYearEnd':"December",
    'ForwardPE':"15.55",
    'GrossProfitTTM':"32688000000",
    'Industry':"COMPUTER & OFFICE EQUIPMENT",
    'LatestQuarter':"2023-03-31",
    'MarketCapitalization':"117037916000",
    'Name': "International Business Machines",
    'OperatingMarginTTM': "0.132",
    'PEGRatio': "1.276",
    'PERatio': "57.54",
    'PriceToBookRatio' : "6.75",
    'PriceToSalesRatioTTM': "2.108",
    'ProfitMargin': "0.0303",
    'QuarterlyEarningsGrowthYOY' : "0.253",
    'QuarterlyRevenueGrowthYOY':"0.004",
    'ReturnOnAssetsTTM':"0.0376",
    'ReturnOnEquityTTM':"0.101",
    'RevenuePerShareTTM':"66.97",
    'RevenueTTM':"60585001000",
    'Sector':"TECHNOLOGY",
    'SharesOutstanding':"908045000",
    'Symbol':"IBM",
    'TrailingPE':"57.54",
}
  // ticker needs to come from query string
  const ticker = "IBM"
  const url = `https://www.alphavantage.co/query?function=OVERVIEW&symbol=${ticker}&apikey=8RH7ENJ1V5RMOK11}`;

  const GetData = async () => {

    if (apiOn) {
      const response = await fetch(url);
      const data = await response.json();
      stockData = date;
      console.log(data);
    }
  }
  GetData();

  console.log(stockData);

  const [value, setValue] = useState(0);

  const handleChange = (event, newValue) => {
    setValue(newValue);
  };

  return (
    <Box sx={{ margin: '3%', borderStyle: 'solid' }}>
      <Box sx={{ borderBottom: 1, borderColor: 'divider' }}>
        <Tabs value={value} onChange={handleChange} aria-label="basic tabs example">
          <Tab label="Company Overview" {...a11yProps(0)} />
          <Tab label="Latest Numbers" {...a11yProps(1)} />
          <Tab label="Item Three" {...a11yProps(2)} />
        </Tabs>
      </Box>
      <TabPanel value={value} index={0} sx={{height: 'fit-content'}}>
        <Box sx={{borderStyle: 'solid', height: '100%'}}>
          <Box sx={{textAlign: 'center'}}>
            <TextField 
              id="CompanyName"
              sx={{width: '100%', marginBottom: '20px'}}
              label="Company Name"
              defaultValue={`${stockData.Name} (${stockData.Symbol})`}
              variant="standard"
              InputProps={{readOnly:true, style:{fontSize:'xx-large'}}}
              />
          </Box>
          <Box sx={{display: 'inline-flex', width: '100%', marginBottom: '20px'}}>
            <TextField 
              id="Industry"
              label="Industry"
              defaultValue={`${stockData.Industry}`}
              variant="standard"
              sx={{margin: '5px', width: '33%'}}
              InputProps={{readOnly:true}}
              />
               <TextField 
              id="Sector"
              label="Sector"
              defaultValue={`${stockData.Sector}`}
              variant="standard"
              sx={{margin: '5px', width: '33%'}}
              InputProps={{readOnly:true}}
              />
              <TextField 
              id="Type"
              label="Type"
              defaultValue={`${stockData.AssetType}`}
              variant="standard"
              sx={{margin: '5px', width: '33%'}}
              InputProps={{readOnly:true}}
              />
          </Box>
          <Box>
            <Typography 
              variant="body1"
              component="span"
              >{stockData.Description}
              </Typography>
          </Box>
        </Box>
      </TabPanel>
      <TabPanel value={value} index={1}>
        Item Two
      </TabPanel>
      <TabPanel value={value} index={2}>
        Item Three
      </TabPanel>
    </Box>
  );
}